# Header
menu:
  Home: /
  Archives: /archives
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-27155459-3
favicon: /img/favicon.ico
twitter:
#google_plus:
#fb_admins:
#fb_app_id:
